"""Declarative config schema for the argos memory provider.

Surfaces configuration in the Hermes desktop UI config panel. This file
only imports from plugins.memory.config_schema (pure data, no agent runtime).
"""
from __future__ import annotations

from plugins.memory.config_schema import (
    ProviderConfigSchema,
    ProviderField,
    ProviderFieldOption,
    KIND_TEXT,
    KIND_SELECT,
    KIND_SECRET,
    KIND_BOOL,
    KIND_NUMBER,
    STORAGE_FLAT_JSON,
)

# `config_file` exists on the maintainer's fork but is NOT a field on stock
# Hermes v0.20.5's ProviderConfigSchema. Passing it unconditionally crashes
# schema load with TypeError on stock (Hermes swallows it → provider shows
# with NO config panel). Only pass it when the running Hermes supports it, so
# fresh installs on stock just work while the fork keeps the native path.
_schema_kwargs: dict = {
    "name": "argos",
    "label": "Argos (Local)",
    "storage": STORAGE_FLAT_JSON,
}
if "config_file" in getattr(ProviderConfigSchema, "__dataclass_fields__", {}):
    _schema_kwargs["config_file"] = "hybrid_memory.json"

CONFIG_SCHEMA = ProviderConfigSchema(
    **_schema_kwargs,
    fields=(
        ProviderField(
            key="local_embedding_model",
            label="Embedding model",
            kind=KIND_TEXT,
            default="BAAI/bge-small-en-v1.5",
            description="Sentence-transformers model for local embeddings (~130MB).",
            info="If the model fails to load, the plugin falls back to text search automatically.",
            inline=True,
            group="Embeddings",
        ),
        ProviderField(
            key="max_injected_items",
            label="Max injected memories",
            kind=KIND_NUMBER,
            default="20",
            description="Maximum memories auto-injected as context before each turn.",
            inline=True,
            group="Retrieval",
        ),
        ProviderField(
            key="inject_content_char_cap",
            label="Injected memory char cap",
            kind=KIND_NUMBER,
            default="800",
            description="Per-memory character cap in the auto-injected recall block. 800 covers ~97% of a personal store with no truncation; raise only if long facts are being cut.",
            inline=True,
            group="Retrieval",
        ),
        ProviderField(
            key="auto_extract",
            label="Auto-extract facts",
            kind=KIND_BOOL,
            default="true",
            description="Extract memory proposals from each conversation turn.",
            info="When enabled, generic patterns and optional LLM fallback create pending proposals. They are not active memory until reviewed; the agent can save explicitly via memory_save.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="llm_fallback",
            label="LLM fallback extraction",
            kind=KIND_BOOL,
            default="true",
            description="Use the host LLM to create proposals when patterns miss facts.",
            info="Adds latency and token cost per turn, but proposals remain pending until reviewed. Disable for regex-only proposals.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="extraction_shadow_diff",
            label="Extraction shadow-diff",
            kind=KIND_BOOL,
            default="false",
            description="Run LLM extraction in parallel with regex and log the diff (validation mode).",
            info="When enabled, always runs LLM extraction alongside regex and logs what each found that the other missed. Does NOT change the actual proposals created — purely attributetic for evaluating LLM-first extraction. Adds latency + token cost on every turn. Check logs for SHADOW_DIFF entries.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="auto_review",
            label="Automatic proposal review",
            kind=KIND_BOOL,
            default="true",
            description="Have the auxiliary LLM review new proposals.",
            info="Obvious junk is quarantined automatically; sensitive or contextless proposals stay pending for confirmation.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="stale_review_sweep_enabled",
            label="Stale-pending sweep",
            kind=KIND_BOOL,
            default="true",
            description="Re-review proposals stranded in 'pending' after a failed or rate-limited reviewer call.",
            info="A rate-limit hiccup no longer condemns a proposal to sit unreviewed forever. Bound by the interval/age/batch fields below.",
            group="Extraction",
        ),
        ProviderField(
            key="stale_review_interval_min",
            label="Stale sweep interval (min)",
            kind=KIND_NUMBER,
            default="15",
            description="How often the stale-pending sweep runs (minutes, >= 1).",
            group="Extraction",
        ),
        ProviderField(
            key="stale_review_min_age_min",
            label="Stale age threshold (min)",
            kind=KIND_NUMBER,
            default="30",
            description="A pending proposal counts as stale once older than this (minutes, >= 0).",
            group="Extraction",
        ),
        ProviderField(
            key="stale_review_max_batch",
            label="Stale sweep batch size",
            kind=KIND_NUMBER,
            default="25",
            description="Maximum proposals the sweep re-reviews per run (1-500).",
            group="Extraction",
        ),
        ProviderField(
            key="extraction_dup_threshold",
            label="Extraction dedupe threshold",
            kind=KIND_TEXT,
            default="0.88",
            description="Minimum embedding cosine similarity for a proposed fact to be skipped as already covered by an active memory (0.0-1.0).",
            info="Before a proposal is created, its content is embedded and compared (top-1) against active memories. Cosine >= this threshold means the fact is already in the cabinet, so no candidate is emitted. Set to 1.0 to disable semantic dedupe (exact-content dedupe still applies). Local embedder only; any embedder error fails soft to normal capture.",
            group="Extraction",
        ),
        ProviderField(
            key="graph_aware_retrieval",
            label="Graph-aware retrieval",
            kind=KIND_BOOL,
            default="true",
            description="Boost memories supported by graph entities during normal search.",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_retrieval_boost",
            label="Graph boost strength",
            kind=KIND_TEXT,
            default="0.0",
            description="Maximum similarity boost for graph-supported memories (0.0–0.5).",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_inject_candidates",
            label="Inject graph-only candidates",
            kind=KIND_BOOL,
            default="false",
            description="Add memories found only by the graph (not by semantic search) into results.",
            info="Off by default; injecting graph-only candidates adds noise that hurt recall in benchmarks.",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_boost_min_similarity",
            label="Graph boost min similarity",
            kind=KIND_TEXT,
            default="0.15",
            description="Minimum semantic similarity for a memory to receive the graph boost (0.0–1.0).",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_traversal_enabled",
            label="Graph traversal (relationship BFS)",
            kind=KIND_BOOL,
            default="true",
            description="Traverse the relationship graph from seed entities to surface related memories (typed-relation BFS).",
            info="Enabled live since graph traversal shipped. Bounded by the depth and boost fields below; seeds come from search hits that clear the seed gate.",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_traversal_depth",
            label="Graph traversal depth",
            kind=KIND_NUMBER,
            default="2",
            description="How many hops the relationship BFS may traverse from a seed entity (1-4).",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_traversal_boost",
            label="Graph traversal boost",
            kind=KIND_TEXT,
            default="0.60",
            description="Similarity boost for memories reached via graph traversal (0.0-1.0).",
            group="Retrieval",
        ),
        ProviderField(
            key="alias_expansion_boost",
            label="Alias expansion boost",
            kind=KIND_TEXT,
            default="0.7",
            description="Similarity boost applied when a query alias resolves to its canonical graph entity (0.0-1.0).",
            group="Retrieval",
        ),
        ProviderField(
            key="consolidation_enabled",
            label="Automatic consolidation",
            kind=KIND_BOOL,
            default="false",
            description="Enable reversible maintenance of expired and duplicate memories at session end.",
            info="Disabled by default; use memory_maintenance with dry_run=true to preview candidates.",
            group="Maintenance",
        ),
        ProviderField(
            key="duplicate_min_similarity",
            label="Semantic dedup threshold",
            kind=KIND_TEXT,
            default="0.88",
            description="Minimum embedding cosine similarity for two memories to be considered semantic near-duplicates (0.0–1.0). Conservative default; tune from real cluster examples.",
            info="Pairs with cosine ≥ this threshold are candidates for quarantine (lower-quality one quarantined, keeper stays). Within-category only. Quarantine is reversible via memory_restore.",
            group="Maintenance",
        ),
        ProviderField(
            key="duplicate_semantic_max_pairs",
            label="Semantic dedup pair limit",
            kind=KIND_TEXT,
            default="20000",
            description="Maximum pairwise comparisons per consolidate() run. Bounds detection time on large stores.",
            group="Maintenance",
        ),
        ProviderField(
            key="consolidation_min_age_days",
            label="Consolidation min age (days)",
            kind=KIND_NUMBER,
            default="30",
            description="Temporary memories younger than this are never consolidated (>= 1 day).",
            group="Maintenance",
        ),
        ProviderField(
            key="consolidation_max_actions",
            label="Consolidation max actions",
            kind=KIND_NUMBER,
            default="25",
            description="Maximum quarantines per consolidation run (1-500).",
            group="Maintenance",
        ),
        ProviderField(
            key="reranker_enabled",
            label="Cross-encoder re-ranking",
            kind=KIND_BOOL,
            default="false",
            description="Re-rank top candidates with a cross-encoder for better relevance.",
            info="Uses BAAI/bge-reranker-base (~420MB, downloaded on first use). Experimental: may improve or regress ranking quality. Adds ~300ms per query on CPU. Enable and evaluate with your query set before relying on it.",
            group="Retrieval",
        ),
        ProviderField(
            key="reranker_model",
            label="Reranker model",
            kind=KIND_TEXT,
            default="BAAI/bge-reranker-base",
            description="HuggingFace model ID for the cross-encoder reranker.",
            group="Retrieval",
        ),
        ProviderField(
            key="reranker_top_n",
            label="Reranker pool size",
            kind=KIND_TEXT,
            default="10",
            description="Number of top candidates to re-rank (5-100). Higher = better ranking but slower.",
            group="Retrieval",
        ),
        ProviderField(
            key="external_sources_require_confirmation",
            label="External sources require confirmation",
            kind=KIND_BOOL,
            default="true",
            description="Memory from external/untrusted channels (email, web, imports) stays pending until a human confirms.",
            info="When enabled, candidates tagged external_source can NEVER auto-activate: the reviewer short-circuits to pending_user_confirmation even when its LLM review would have approved, and the storage boundary blocks auto_review activation. Inbound security scanning of external evidence runs regardless — scan-blocked content always routes to pending for a human. On by default: out-of-the-box installs enforce the human-confirmation boundary for external sources.",
            group="Security",
        ),
        ProviderField(
            key="context_aware_retrieval",
            label="Context-aware retrieval",
            kind=KIND_BOOL,
            default="true",
            description="Prepend recent conversation context to queries with pronouns/references.",
            info="When a query contains words like 'that', 'he', 'the thing', the last few user messages are prepended to give the embedder context to resolve the reference. Zero latency cost, no LLM calls.",
            group="Retrieval",
        ),
        ProviderField(
            key="context_window_size",
            label="Context window size",
            kind=KIND_TEXT,
            default="3",
            description="Number of recent user messages to use as context (1-10).",
            group="Retrieval",
        ),
        ProviderField(
            key="context_max_chars",
            label="Context max chars",
            kind=KIND_TEXT,
            default="500",
            description="Maximum total characters of context to prepend (100-2000).",
            group="Retrieval",
        ),
        ProviderField(
            key="query_expansion_enabled",
            label="Query expansion",
            kind=KIND_BOOL,
            default="true",
            description="Expand weak queries into sub-queries via LLM for better recall.",
            info="Only fires when the top search result is below a similarity floor (weak results). Uses the host's auxiliary LLM client. Cached for 1 hour. Fail-soft: returns original results if the LLM call fails. Adds ~1-3s latency only on weak queries.",
            group="Retrieval",
        ),
        ProviderField(
            key="query_expansion_similarity_floor",
            label="Expansion similarity floor",
            kind=KIND_TEXT,
            default="0.3",
            description="Trigger expansion when top hit similarity is below this (0.0-1.0).",
            group="Retrieval",
        ),
        ProviderField(
            key="llm_model",
            label="LLM model",
            kind=KIND_TEXT,
            default="",
            description="Model ID for auxiliary LLM tasks (extraction, review, query expansion). Empty = use auxiliary client default.",
            info="Example: 'google/gemini-3.6-flash', 'openai/gpt-4o-mini', 'anthropic/claude-3.5-sonnet'. Leave empty to use the host's configured auxiliary model. Changing this updates all LLM-based memory operations.",
            group="LLM",
        ),
        ProviderField(
            key="entity_aliases",
            label="Entity aliases",
            kind=KIND_TEXT,
            default="",
            description="JSON mapping of aliases to canonical entity names for retrieval.",
            info='Example: {"my role": "Entity-A", "the role": "Entity-A", "the project": "Project-X"}. When a search query contains an alias, the system also searches for the canonical entity in the graph. This fixes "tell me about my role" failing to find Entity-A memories.',
            group="Retrieval",
        ),
        ProviderField(
            key="role_words",
            label="Role words",
            kind=KIND_TEXT,
            default="",
            description="Extra role words for alias extraction (comma-separated or JSON array).",
            info='Role words like "wife", "therapist", "boss" enable "my X is Name" alias extraction. Defaults include 40+ common roles; add your own here. LLM-learned words are auto-added to this list.',
            group="Retrieval",
        ),
        ProviderField(
            key="role_alias_llm_fallback",
            label="LLM role-word learning",
            kind=KIND_BOOL,
            default="true",
            description="When an unknown word appears in \"my X is Name\", ask the LLM if X is a person-role.",
            info="Self-extending: learned role words are persisted to role_words so future occurrences are regex-fast. Cost asymptotes toward zero as the vocabulary fills.",
            group="LLM",
        ),
        ProviderField(
            key="llm_provider",
            label="LLM provider",
            kind=KIND_TEXT,
            default="",
            description="Provider override for auxiliary LLM tasks. Empty = use auxiliary client default.",
            info="Example: 'openrouter', 'openai', 'anthropic'. Leave empty to use the host's configured provider.",
            group="LLM",
        ),
        ProviderField(
            key="extraction_llm_model",
            label="Extraction LLM model",
            kind=KIND_TEXT,
            default="",
            description="Model ID for document-fact extraction (Spec-07 D5). Empty = use llm_model / auxiliary default.",
            info="Separate model for the watcher's extraction pass. Use a cheaper/faster model for bulk doc extraction while keeping the memory-ops model higher quality. Empty = falls back to llm_model, then auxiliary client default.",
            group="LLM",
        ),
        ProviderField(
            key="extraction_llm_provider",
            label="Extraction LLM provider",
            kind=KIND_TEXT,
            default="",
            description="Provider override for document-fact extraction. Empty = use llm_provider / auxiliary default.",
            info="Example: 'openrouter', 'openai', 'anthropic'. For the local SKU v2, set to a zero-retention enterprise endpoint. Empty = falls back to llm_provider, then auxiliary client default.",
            group="LLM",
        ),
        ProviderField(
            key="answering_llm_model",
            label="Answering LLM model",
            kind=KIND_TEXT,
            default="",
            description="Model ID for answering (read by the host agent). Empty = use the host's configured model.",
            info="This is a hint to the host agent about which model to use for answering when memory context is injected. The plugin itself does not generate answers — this config is read by the host. Empty = host default.",
            group="LLM",
        ),
        ProviderField(
            key="answering_llm_provider",
            label="Answering LLM provider",
            kind=KIND_TEXT,
            default="",
            description="Provider override for answering (read by the host agent). Empty = use the host's configured provider.",
            info="For the local SKU v2, set to a zero-retention enterprise endpoint. The plugin exposes this for the host to read; it does not make answering LLM calls itself. Empty = host default.",
            group="LLM",
        ),
        ProviderField(
            key="storage_mode",
            label="Storage mode",
            kind=KIND_SELECT,
            default="shared_service",
            description="Use one local memory service for all Hermes surfaces.",
            info="Shared service prevents desktop/gateway split-brain and DuckDB writer locks. Direct mode is for attributetics only.",
            options=(
                ProviderFieldOption("shared_service", "Shared service"),
                ProviderFieldOption("local", "Direct files"),
            ),
            group="Storage",
        ),
        ProviderField(
            key="deployment_mode",
            label="Deployment mode",
            kind=KIND_SELECT,
            default="cloud_pilot",
            description="POPIA deployment mode: cloud-first pilot or local SKU v2 (hybrid).",
            info="cloud_pilot: runs on the hosted processing service (operator's own data, engagement-consent covers it). local_sku: data never leaves the practice's premises (POPIA §72 avoidance). Switching = config change + restart, never a code path change. See Annexure A for the full data-flow and legal posture.",
            options=(
                ProviderFieldOption("cloud_pilot", "Cloud pilot (hosted)"),
                ProviderFieldOption("local_sku", "Local SKU v2 (on-prem)"),
            ),
            group="Deployment",
        ),
        ProviderField(
            key="data_residency",
            label="Data residency",
            kind=KIND_SELECT,
            default="cloud",
            description="Where memory data is stored: cloud (hosted) or local (on-prem).",
            info="cloud: memory store on the hosted service. local: memory store on the practice's premises — zero cross-border transfer. Must match deployment_mode. The plugin does not move data itself; this flag controls provider routing and audit labelling.",
            options=(
                ProviderFieldOption("cloud", "Cloud (hosted)"),
                ProviderFieldOption("local", "Local (on-prem)"),
            ),
            group="Deployment",
        ),
        ProviderField(
            key="database_filename",
            label="DuckDB filename",
            kind=KIND_TEXT,
            default="hybrid_memory.duckdb",
            description="DuckDB database filename (stored in HERMES_HOME).",
            group="Storage",
        ),
        ProviderField(
            key="graph_dirname",
            label="Kuzu graph directory",
            kind=KIND_TEXT,
            default="hybrid_memory_kuzu",
            description="Kuzu graph database directory (stored in HERMES_HOME).",
            group="Storage",
        ),
        ProviderField(
            key="chain_unfold",
            label="Chain unfold",
            kind=KIND_SELECT,
            default="auto",
            description="Auto-inject a compact version arc when the query signals change-intent and a top result has a history.",
            info="AUTO by default (matches runtime). The memory_chain tool is always available on-demand; auto injects a version arc only on change-intent queries. Set 'off' to disable auto-injection, 'always' to inject on every chained result.",
            options=(
                ProviderFieldOption("off", "Off (on-demand only)"),
                ProviderFieldOption("auto", "Auto (change-intent trigger)"),
                ProviderFieldOption("always", "Always (every chained result)"),
            ),
            group="Chains",
        ),
        ProviderField(
            key="chain_max_versions",
            label="Chain max versions",
            kind=KIND_TEXT,
            default="3",
            description="Most recent versions to inject per chain unfold (1-10).",
            group="Chains",
        ),
        ProviderField(
            key="chain_max_inject",
            label="Chain inject token cap",
            kind=KIND_TEXT,
            default="150",
            description="Soft token cap per chain unfold (rough 4 chars/token estimate).",
            group="Chains",
        ),
        ProviderField(
            key="chain_unfold_top_k",
            label="Chain unfold top-K",
            kind=KIND_TEXT,
            default="3",
            description="How many top search results to scan for a chain anchor (1-20). The per-candidate similarity floor is the precision guard.",
            group="Chains",
        ),
        ProviderField(
            key="chain_unfold_query_fallback",
            label="Chain unfold query fallback",
            kind=KIND_SELECT,
            default="false",
            description="When no top-K result has a chain, search deeper for a chain matching the query (same similarity floor).",
            options=(
                ProviderFieldOption("false", "Off"),
                ProviderFieldOption("true", "On (deeper search fallback)"),
            ),
            group="Chains",
        ),
        ProviderField(
            key="chain_unfold_min_similarity",
            label="Chain unfold min similarity",
            kind=KIND_TEXT,
            default="0.30",
            description="A chained result only unfolds when its raw similarity is at least this (0.0-1.0). Precision gate.",
            group="Chains",
        ),
        ProviderField(
            key="router_enabled",
            label="Intent routing (answerer)",
            kind=KIND_BOOL,
            default="false",
            description="Route the answerer model per-turn: temporal/multi-hop queries go to the smart model, everything else to the default model.",
            info="Ships OFF. Lightweight regex-based detection (no extra token cost). The core honors the returned model for that turn and reverts automatically. Saves the smart model (~10x cost) for the queries that need it — the measured +26pp temporal win comes from routing date-math questions to the smarter model.",
            inline=True,
            group="Routing",
        ),
        ProviderField(
            key="router_smart_model",
            label="Smart model (temporal/multi-hop)",
            kind=KIND_TEXT,
            default="",
            description="Model used when a temporal or multi-hop query is detected.",
            info="Example: 'deepseek/deepseek-v4-pro' (or your provider's stronger model). This is the model that handles 'how many days since', 'when did X', 'before Y'. Costlier per call but only fires on routed turns.",
            group="Routing",
        ),
        ProviderField(
            key="router_smart_provider",
            label="Smart model provider",
            kind=KIND_TEXT,
            default="",
            description="Provider for the smart model. Empty = same provider as the default model.",
            info="Example: 'opencode-go'. Leave empty to keep the agent's current provider.",
            group="Routing",
        ),
        ProviderField(
            key="router_default_model",
            label="Default model (everything else)",
            kind=KIND_TEXT,
            default="",
            description="Model used for ordinary (non-temporal) turns. Empty = leave the current answerer unchanged.",
            info="Example: 'deepseek/deepseek-v4-flash'. Set this to your fast/cheap day-to-day model so ordinary turns stay cheap and the router clearly splits traffic.",
            group="Routing",
        ),
        ProviderField(
            key="router_default_provider",
            label="Default model provider",
            kind=KIND_TEXT,
            default="",
            description="Provider for the default model. Empty = same provider as the smart model.",
            info="Example: 'opencode-go'.",
            group="Routing",
        ),
        ProviderField(
            key="router_subcall_enabled",
            label="Cheap temporal sub-call (trimmed context)",
            kind=KIND_BOOL,
            default="false",
            description="When ON, temporal/multi-hop queries use a small smart-model sub-call (question + few dated memories) instead of switching the whole ~124k-token turn to the smart model.",
            info="Switching the whole turn sends the full context (history + memory injection + tools) to the expensive model — ~R2.50 per temporal query. ON instead fires ONE cheap smart-model call on a trimmed context (~1-2k tokens, ~R0.03) and injects the answer as a hint, keeping everything on Flash. Fail-soft: if the sub-call fails, Flash answers normally.",
            group="Routing",
        ),
        ProviderField(
            key="chronological_injection",
            label="Chronological injection (temporal)",
            kind=KIND_BOOL,
            default="false",
            description="On temporal/multi-hop turns, re-sort the injected memories by timestamp (oldest first) so the model reads a timeline in order instead of relevance-scrambled order.",
            info="Ships OFF. Fixes 'temporal whiplash' — when a 'when did / how long ago / what happened first' question retrieves memories in relevance order, the model sees events out of sequence. This only re-orders the injection for temporal queries; ordinary turns keep relevance order. No token cost; reuse of the P2A temporal classifier.",
            inline=True,
            group="Temporal",
        ),
        ProviderField(
            key="date_anchor_rerank",
            label="Date-anchored re-rank (temporal)",
            kind=KIND_BOOL,
            default="false",
            description="On temporal turns with an explicit date expression ('10 days ago', 'last Tuesday', 'on March 2nd'), re-sort injected memories by proximity to the resolved target date.",
            info="Ships OFF pending drip confirmation. Zero-LLM (regex resolve vs today + stable sort). Measured +10pp on extractable questions (n=20, Flash) with control arm exactly flat. Reorders only when the intent router says temporal AND a date expression is found; otherwise keeps relevance order.",
            inline=True,
                        group="Temporal",
                    ),
                    ProviderField(
                        key="freshness_markers",
                        label="Freshness markers (date-anchored)",
                        kind=KIND_BOOL,
                        default="true",
                        description="When a recalled memory contains an explicit date anchor ('26/8', 'PR #96224', 'last week'), append a compact as-of marker built from the memory's own update timestamp so a stale anchor is never read as current.",
                        info="Ships ON. Zero-LLM regex; only date-bearing rows get the marker (a few tokens each). Guards the 'stale date presented as current' failure class without touching ranking or retrieval. Benchmark-parity note: changes injected text only for date-anchored rows — gate on the 100-q own-corpus A/B if sensitivity is required.",
                        inline=True,
                        group="Temporal",
                    ),
                    ProviderField(
                        key="history_at_current_time",
            label="History at current time (temporal)",
            kind=KIND_BOOL,
            default="true",
            description="On historical queries ('where did I use to live', 'what was my old job'), include superseded versions of memories in retrieval so past facts stay answerable.",
            info="Ships ON. Fixes 'where did X use to Y' returning nothing: closed versions were filtered out entirely at current-time queries. Precision-first detector (question shape AND explicit past marker) gates the widened search; closed rows are labelled '(previously)' at injection so the model never reads them as current truth. as_of precedence preserved; ordinary queries unchanged.",
            inline=True,
            group="Temporal",
        ),
        ProviderField(
            key="expiry_enabled",
            label="Expiry enabled",
            kind=KIND_BOOL,
            default="false",
            description="Allow memories to carry a best-before date (expires_at). Off = current behavior exactly.",
            info="When enabled, memories can be saved with a durability ('temporary' triggers the TTL map) or an explicit expiry date. Expired memories are excluded from retrieval but never deleted; use memory_search(include_expired=true) to audit them and memory_update(expires_at=null) to revive.",
            inline=True,
            group="Expiry",
        ),
        ProviderField(
            key="expiry_ttl_days",
            label="TTL days by category",
            kind=KIND_TEXT,
            default='{"context_note":30,"event":180,"goal":180}',
            description="Shelf life in days applied when a memory is saved/approved as temporary. JSON map category→days.",
            group="Expiry",
        ),
        ProviderField(
            key="expiry_default_days",
            label="Fallback TTL days",
            kind=KIND_NUMBER,
            default="90",
            description="Used when the saved category is not in the TTL map and the memory is temporary.",
            group="Expiry",
        ),
        ProviderField(
            key="expiry_auto_suggest",
            label="Suggest expiry on review",
            kind=KIND_BOOL,
            default="false",
            description="When the reviewer approves a context_note/event/goal candidate, propose an expiry (deterministic, no LLM). User confirms before it sticks.",
            inline=True,
            group="Expiry",
        ),
        # -- Distillation (P4.2) -------------------------------------------
        ProviderField(
            key="distillation_enabled",
            label="Distillation pass (the dream)",
            kind=KIND_BOOL,
            default="false",
            description="At session end, run an LLM-assisted pass that proposes insights, guardrails, and contradiction surfaces from recent memories + feedback. Proposals only — nothing is active until reviewed.",
            info="Ships OFF. When enabled, runs after consolidation at session end. Bounded by novelty gate (min new records), cooldown, and call budget. Reuses llm_model/llm_provider. Typical cost R0.10-0.60/run; worst ~R10-15/month with 24h cooldown.",
            inline=True,
            group="Distillation",
        ),
        ProviderField(
            key="distillation_min_new_records",
            label="Min new records",
            kind=KIND_NUMBER,
            default="20",
            description="Minimum eligible records created/updated since the last run to trigger a new pass.",
            group="Distillation",
        ),
        ProviderField(
            key="distillation_cooldown_hours",
            label="Cooldown hours",
            kind=KIND_NUMBER,
            default="24",
            description="Minimum hours since the last completed run before another can start.",
            group="Distillation",
        ),
        ProviderField(
            key="distillation_max_records_per_run",
            label="Max records per run",
            kind=KIND_NUMBER,
            default="100",
            description="Maximum records sampled per run (newest first).",
            group="Distillation",
        ),
        ProviderField(
            key="distillation_max_calls",
            label="Max LLM calls per run",
            kind=KIND_NUMBER,
            default="10",
            description="Maximum LLM calls per run (1 per cluster + 1 high-signal scan). Bounds cost.",
            group="Distillation",
        ),
        # -- Lifecycle (P5.1, #6) -------------------------------------------
        ProviderField(
            key="archive_enabled",
            label="Archival tier",
            kind=KIND_BOOL,
            default="false",
            description="At session end, archive records older than archive_after_days with no retrievals/feedback. Archived = out of injection pool, still searchable via include_archived.",
            info="Ships OFF. Deterministic, zero LLM. Exempt: facts, preferences, insights, relationships, goal. Any update/feedback revives. Conservative — enable after soak.",
            inline=True,
            group="Lifecycle",
        ),
        ProviderField(
            key="archive_after_days",
            label="Archive after (days)",
            kind=KIND_NUMBER,
            default="180",
            description="Records older than this (by created_at) with no retrievals/feedback are archived.",
            group="Lifecycle",
        ),
        ProviderField(
            key="forget_enabled",
            label="Forgetting",
            kind=KIND_BOOL,
            default="false",
            description="Auto-quarantine context_note/event/goal older than forget_after_days with no retrievals/feedback. Reversible — quarantine, never delete.",
            info="Ships OFF. Deterministic, zero LLM. Only context_note/event/goal categories — facts/preferences/insights/relationships are never forgotten. Restore via memory_restore.",
            inline=True,
            group="Lifecycle",
        ),
        ProviderField(
            key="forget_after_days",
            label="Forget after (days)",
            kind=KIND_NUMBER,
            default="365",
            description="context_note/event/goal records older than this with no retrievals/feedback are quarantined.",
            group="Lifecycle",
        ),
        ProviderField(
            key="rollup_enabled",
            label="Long-horizon rollups",
            kind=KIND_BOOL,
            default="false",
            description="Monthly LLM pass that emits profile-style 'what has stayed true / changed' summaries as proposals. Proposals only — never writes active memory.",
            info="Ships OFF. Reuses P4.2 distillation seam (novelty gate, cooldown, call budget, fail-soft). Typical cost R0.10-0.60/run.",
            inline=True,
            group="Lifecycle",
        ),
        ProviderField(
            key="rollup_interval_days",
            label="Rollup interval (days)",
            kind=KIND_NUMBER,
            default="30",
            description="Minimum days between rollup runs.",
            group="Lifecycle",
        ),
        ProviderField(
            key="rollup_max_records_per_run",
            label="Rollup max records",
            kind=KIND_NUMBER,
            default="100",
            description="Maximum records sampled per rollup run (oldest active low-retrieval first).",
            group="Lifecycle",
        ),
        ProviderField(
            key="local_only",
            label="Local-only mode",
            kind=KIND_BOOL,
            default="false",
            description="Block every plugin-owned LLM call (extraction, review, graph typing, expansion, temporal sub-call, distillation).",
            info="When ON, no stored or conversational memory data is sent to any LLM by this plugin — all egress sites fail soft (regex-only extraction, proposals wait for user review, no expansion, no sub-call hints). Embeddings are always local. See scripts/egress_report.py for the full inventory.",
            group="Privacy",
        ),
        # -- Backup (cross-platform, service-coordinated) ---------------------
        ProviderField(
            key="backup_enabled",
            label="Enable scheduled backup",
            kind=KIND_BOOL,
            default="false",
            description="Enable service-coordinated backup via EXPORT DATABASE (FORMAT PARQUET). Cross-platform, no downtime, no elevation.",
            info="Backup runs inside the memory service (the sole DB writer). CHECKPOINT + EXPORT gives a crash-consistent, type-faithful logical dump. Restore via backup_cli.py restore (service must be stopped). The Kuzu graph is derived data — rebuild via backfill_graph.py after restore.",
            inline=True,
            group="Backup",
        ),
        ProviderField(
            key="backup_dst_root",
            label="Backup destination",
            kind=KIND_TEXT,
            default="",
            description="Root directory for snapshot folders. Empty = <HERMES_HOME>/backups/memory.",
            info="Point this at a different volume (D:, NAS, removable) to protect against disk failure. Same-volume backups protect against corruption only.",
            inline=True,
            group="Backup",
        ),
        ProviderField(
            key="backup_retention_snapshots",
            label="Snapshots to keep",
            kind=KIND_NUMBER,
            default="6",
            description="Number of verified snapshots to retain. Oldest pruned after the new one verifies.",
            inline=True,
            group="Backup",
        ),
    ),
)
