"""Declarative config schema for the hybrid_memory memory provider.

Surfaces configuration in the Hermes desktop UI config panel. This file
only imports from plugins.memory.config_schema (pure data, no agent runtime).
"""
from __future__ import annotations

from plugins.memory.config_schema import (
    ProviderConfigSchema,
    ProviderField,
    ProviderFieldOption,
    KIND_TEXT,
    KIND_SELECT,
    KIND_SECRET,
    KIND_BOOL,
    KIND_NUMBER,
    STORAGE_FLAT_JSON,
)

CONFIG_SCHEMA = ProviderConfigSchema(
    name="hybrid_memory",
    label="Argos (Local)",
    storage=STORAGE_FLAT_JSON,
    config_file="hybrid_memory.json",
    fields=(
        ProviderField(
            key="local_embedding_model",
            label="Embedding model",
            kind=KIND_TEXT,
            default="BAAI/bge-small-en-v1.5",
            description="Sentence-transformers model for local embeddings (~130MB).",
            info="If the model fails to load, the plugin falls back to text search automatically.",
            inline=True,
            group="Embeddings",
        ),
        ProviderField(
            key="max_injected_items",
            label="Max injected memories",
            kind=KIND_NUMBER,
            default="8",
            description="Maximum memories auto-injected as context before each turn.",
            inline=True,
            group="Retrieval",
        ),
        ProviderField(
            key="inject_content_char_cap",
            label="Injected memory char cap",
            kind=KIND_NUMBER,
            default="800",
            description="Per-memory character cap in the auto-injected recall block. 800 covers ~97% of a personal store with no truncation; raise only if long facts are being cut.",
            inline=True,
            group="Retrieval",
        ),
        ProviderField(
            key="auto_extract",
            label="Auto-extract facts",
            kind=KIND_BOOL,
            default="true",
            description="Extract memory proposals from each conversation turn.",
            info="When enabled, generic patterns and optional LLM fallback create pending proposals. They are not active memory until reviewed; the agent can save explicitly via memory_save.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="llm_fallback",
            label="LLM fallback extraction",
            kind=KIND_BOOL,
            default="true",
            description="Use the host LLM to create proposals when patterns miss facts.",
            info="Adds latency and token cost per turn, but proposals remain pending until reviewed. Disable for regex-only proposals.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="extraction_shadow_diff",
            label="Extraction shadow-diff",
            kind=KIND_BOOL,
            default="false",
            description="Run LLM extraction in parallel with regex and log the diff (validation mode).",
            info="When enabled, always runs LLM extraction alongside regex and logs what each found that the other missed. Does NOT change the actual proposals created — purely attributetic for evaluating LLM-first extraction. Adds latency + token cost on every turn. Check logs for SHADOW_DIFF entries.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="auto_review",
            label="Automatic proposal review",
            kind=KIND_BOOL,
            default="true",
            description="Have the auxiliary LLM review new proposals.",
            info="Obvious junk is quarantined automatically; sensitive or contextless proposals stay pending for confirmation.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="graph_aware_retrieval",
            label="Graph-aware retrieval",
            kind=KIND_BOOL,
            default="true",
            description="Boost memories supported by graph entities during normal search.",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_retrieval_boost",
            label="Graph boost strength",
            kind=KIND_TEXT,
            default="0.05",
            description="Maximum similarity boost for graph-supported memories (0.0–0.5).",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_inject_candidates",
            label="Inject graph-only candidates",
            kind=KIND_BOOL,
            default="false",
            description="Add memories found only by the graph (not by semantic search) into results.",
            info="Off by default; injecting graph-only candidates adds noise that hurt recall in benchmarks.",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_boost_min_similarity",
            label="Graph boost min similarity",
            kind=KIND_TEXT,
            default="0.15",
            description="Minimum semantic similarity for a memory to receive the graph boost (0.0–1.0).",
            group="Retrieval",
        ),
        ProviderField(
            key="consolidation_enabled",
            label="Automatic consolidation",
            kind=KIND_BOOL,
            default="false",
            description="Enable reversible maintenance of expired and duplicate memories at session end.",
            info="Disabled by default; use memory_maintenance with dry_run=true to preview candidates.",
            group="Maintenance",
        ),
        ProviderField(
            key="reranker_enabled",
            label="Cross-encoder re-ranking",
            kind=KIND_BOOL,
            default="false",
            description="Re-rank top candidates with a cross-encoder for better relevance.",
            info="Uses BAAI/bge-reranker-base (~420MB, downloaded on first use). Experimental: may improve or regress ranking quality. Adds ~300ms per query on CPU. Enable and evaluate with your query set before relying on it.",
            group="Retrieval",
        ),
        ProviderField(
            key="reranker_model",
            label="Reranker model",
            kind=KIND_TEXT,
            default="BAAI/bge-reranker-base",
            description="HuggingFace model ID for the cross-encoder reranker.",
            group="Retrieval",
        ),
        ProviderField(
            key="reranker_top_n",
            label="Reranker pool size",
            kind=KIND_TEXT,
            default="10",
            description="Number of top candidates to re-rank (5-100). Higher = better ranking but slower.",
            group="Retrieval",
        ),
        ProviderField(
            key="context_aware_retrieval",
            label="Context-aware retrieval",
            kind=KIND_BOOL,
            default="true",
            description="Prepend recent conversation context to queries with pronouns/references.",
            info="When a query contains words like 'that', 'he', 'the thing', the last few user messages are prepended to give the embedder context to resolve the reference. Zero latency cost, no LLM calls.",
            group="Retrieval",
        ),
        ProviderField(
            key="context_window_size",
            label="Context window size",
            kind=KIND_TEXT,
            default="3",
            description="Number of recent user messages to use as context (1-10).",
            group="Retrieval",
        ),
        ProviderField(
            key="context_max_chars",
            label="Context max chars",
            kind=KIND_TEXT,
            default="500",
            description="Maximum total characters of context to prepend (100-2000).",
            group="Retrieval",
        ),
        ProviderField(
            key="query_expansion_enabled",
            label="Query expansion",
            kind=KIND_BOOL,
            default="true",
            description="Expand weak queries into sub-queries via LLM for better recall.",
            info="Only fires when the top search result is below a similarity floor (weak results). Uses the host's auxiliary LLM client. Cached for 1 hour. Fail-soft: returns original results if the LLM call fails. Adds ~1-3s latency only on weak queries.",
            group="Retrieval",
        ),
        ProviderField(
            key="query_expansion_similarity_floor",
            label="Expansion similarity floor",
            kind=KIND_TEXT,
            default="0.3",
            description="Trigger expansion when top hit similarity is below this (0.0-1.0).",
            group="Retrieval",
        ),
        ProviderField(
            key="llm_model",
            label="LLM model",
            kind=KIND_TEXT,
            default="",
            description="Model ID for auxiliary LLM tasks (extraction, review, query expansion). Empty = use auxiliary client default.",
            info="Example: 'google/gemini-3.6-flash', 'openai/gpt-4o-mini', 'anthropic/claude-3.5-sonnet'. Leave empty to use the host's configured auxiliary model. Changing this updates all LLM-based memory operations.",
            group="LLM",
        ),
        ProviderField(
            key="entity_aliases",
            label="Entity aliases",
            kind=KIND_TEXT,
            default="",
            description="JSON mapping of aliases to canonical entity names for retrieval.",
            info='Example: {"my role": "Entity-A", "the role": "Entity-A", "the project": "Project-X"}. When a search query contains an alias, the system also searches for the canonical entity in the graph. This fixes "tell me about my role" failing to find Entity-A memories.',
            group="Retrieval",
        ),
        ProviderField(
            key="role_words",
            label="Role words",
            kind=KIND_TEXT,
            default="",
            description="Extra role words for alias extraction (comma-separated or JSON array).",
            info='Role words like "wife", "therapist", "boss" enable "my X is Name" alias extraction. Defaults include 40+ common roles; add your own here. LLM-learned words are auto-added to this list.',
            group="Retrieval",
        ),
        ProviderField(
            key="role_alias_llm_fallback",
            label="LLM role-word learning",
            kind=KIND_BOOL,
            default="true",
            description="When an unknown word appears in \"my X is Name\", ask the LLM if X is a person-role.",
            info="Self-extending: learned role words are persisted to role_words so future occurrences are regex-fast. Cost asymptotes toward zero as the vocabulary fills.",
            group="LLM",
        ),
        ProviderField(
            key="llm_provider",
            label="LLM provider",
            kind=KIND_TEXT,
            default="",
            description="Provider override for auxiliary LLM tasks. Empty = use auxiliary client default.",
            info="Example: 'openrouter', 'openai', 'anthropic'. Leave empty to use the host's configured provider.",
            group="LLM",
        ),
        ProviderField(
            key="storage_mode",
            label="Storage mode",
            kind=KIND_SELECT,
            default="shared_service",
            description="Use one local memory service for all Hermes surfaces.",
            info="Shared service prevents desktop/gateway split-brain and DuckDB writer locks. Direct mode is for attributetics only.",
            options=(
                ProviderFieldOption("shared_service", "Shared service"),
                ProviderFieldOption("local", "Direct files"),
            ),
            group="Storage",
        ),
        ProviderField(
            key="database_filename",
            label="DuckDB filename",
            kind=KIND_TEXT,
            default="hybrid_memory.duckdb",
            description="DuckDB database filename (stored in HERMES_HOME).",
            group="Storage",
        ),
        ProviderField(
            key="graph_dirname",
            label="Kuzu graph directory",
            kind=KIND_TEXT,
            default="hybrid_memory_kuzu",
            description="Kuzu graph database directory (stored in HERMES_HOME).",
            group="Storage",
        ),
        ProviderField(
            key="chain_unfold",
            label="Chain unfold",
            kind=KIND_SELECT,
            default="off",
            description="Auto-inject a compact version arc when the query signals change-intent and a top result has a history.",
            info="Ships OFF. The memory_chain tool is always available on-demand; this controls automatic injection. Flip to 'auto' after evaluating with a change-intent query set.",
            options=(
                ProviderFieldOption("off", "Off (on-demand only)"),
                ProviderFieldOption("auto", "Auto (change-intent trigger)"),
                ProviderFieldOption("always", "Always (every chained result)"),
            ),
            group="Chains",
        ),
        ProviderField(
            key="chain_max_versions",
            label="Chain max versions",
            kind=KIND_TEXT,
            default="3",
            description="Most recent versions to inject per chain unfold (1-10).",
            group="Chains",
        ),
        ProviderField(
            key="chain_max_inject",
            label="Chain inject token cap",
            kind=KIND_TEXT,
            default="150",
            description="Soft token cap per chain unfold (rough 4 chars/token estimate).",
            group="Chains",
        ),
        ProviderField(
            key="chain_unfold_top_k",
            label="Chain unfold top-K",
            kind=KIND_TEXT,
            default="3",
            description="How many top search results to scan for a chain anchor (1-20). The per-candidate similarity floor is the precision guard.",
            group="Chains",
        ),
        ProviderField(
            key="chain_unfold_query_fallback",
            label="Chain unfold query fallback",
            kind=KIND_SELECT,
            default="false",
            description="When no top-K result has a chain, search deeper for a chain matching the query (same similarity floor).",
            options=(
                ProviderFieldOption("false", "Off"),
                ProviderFieldOption("true", "On (deeper search fallback)"),
            ),
            group="Chains",
        ),
        ProviderField(
            key="router_enabled",
            label="Intent routing (answerer)",
            kind=KIND_BOOL,
            default="false",
            description="Route the answerer model per-turn: temporal/multi-hop queries go to the smart model, everything else to the default model.",
            info="Ships OFF. Lightweight regex-based detection (no extra token cost). The core honors the returned model for that turn and reverts automatically. Saves the smart model (~10x cost) for the queries that need it — the measured +26pp temporal win comes from routing date-math questions to the smarter model.",
            inline=True,
            group="Routing",
        ),
        ProviderField(
            key="router_smart_model",
            label="Smart model (temporal/multi-hop)",
            kind=KIND_TEXT,
            default="",
            description="Model used when a temporal or multi-hop query is detected.",
            info="Example: 'deepseek/deepseek-v4-pro' (or your provider's stronger model). This is the model that handles 'how many days since', 'when did X', 'before Y'. Costlier per call but only fires on routed turns.",
            group="Routing",
        ),
        ProviderField(
            key="router_smart_provider",
            label="Smart model provider",
            kind=KIND_TEXT,
            default="",
            description="Provider for the smart model. Empty = same provider as the default model.",
            info="Example: 'opencode-go'. Leave empty to keep the agent's current provider.",
            group="Routing",
        ),
        ProviderField(
            key="router_default_model",
            label="Default model (everything else)",
            kind=KIND_TEXT,
            default="",
            description="Model used for ordinary (non-temporal) turns. Empty = leave the current answerer unchanged.",
            info="Example: 'deepseek/deepseek-v4-flash'. Set this to your fast/cheap day-to-day model so ordinary turns stay cheap and the router clearly splits traffic.",
            group="Routing",
        ),
        ProviderField(
            key="router_default_provider",
            label="Default model provider",
            kind=KIND_TEXT,
            default="",
            description="Provider for the default model. Empty = same provider as the smart model.",
            info="Example: 'opencode-go'.",
            group="Routing",
        ),
        ProviderField(
            key="router_subcall_enabled",
            label="Cheap temporal sub-call (trimmed context)",
            kind=KIND_BOOL,
            default="false",
            description="When ON, temporal/multi-hop queries use a small smart-model sub-call (question + few dated memories) instead of switching the whole ~124k-token turn to the smart model.",
            info="Switching the whole turn sends the full context (history + memory injection + tools) to the expensive model — ~R2.50 per temporal query. ON instead fires ONE cheap smart-model call on a trimmed context (~1-2k tokens, ~R0.03) and injects the answer as a hint, keeping everything on Flash. Fail-soft: if the sub-call fails, Flash answers normally.",
            group="Routing",
        ),
        ProviderField(
            key="chronological_injection",
            label="Chronological injection (temporal)",
            kind=KIND_BOOL,
            default="false",
            description="On temporal/multi-hop turns, re-sort the injected memories by timestamp (oldest first) so the model reads a timeline in order instead of relevance-scrambled order.",
            info="Ships OFF. Fixes 'temporal whiplash' — when a 'when did / how long ago / what happened first' question retrieves memories in relevance order, the model sees events out of sequence. This only re-orders the injection for temporal queries; ordinary turns keep relevance order. No token cost; reuse of the P2A temporal classifier.",
            inline=True,
            group="Temporal",
        ),
        ProviderField(
            key="date_anchor_rerank",
            label="Date-anchored re-rank (temporal)",
            kind=KIND_BOOL,
            default="false",
            description="On temporal turns with an explicit date expression ('10 days ago', 'last Tuesday', 'on March 2nd'), re-sort injected memories by proximity to the resolved target date.",
            info="Ships OFF pending drip confirmation. Zero-LLM (regex resolve vs today + stable sort). Measured +10pp on extractable questions (n=20, Flash) with control arm exactly flat. Reorders only when the intent router says temporal AND a date expression is found; otherwise keeps relevance order.",
            inline=True,
            group="Temporal",
        ),
    ),
)
