"""Declarative config schema for the hybrid_memory memory provider.

Surfaces configuration in the Hermes desktop UI config panel. This file
only imports from plugins.memory.config_schema (pure data, no agent runtime).
"""
from __future__ import annotations

from plugins.memory.config_schema import (
    ProviderConfigSchema,
    ProviderField,
    ProviderFieldOption,
    KIND_TEXT,
    KIND_SELECT,
    KIND_SECRET,
    KIND_BOOL,
    KIND_NUMBER,
    STORAGE_FLAT_JSON,
)

CONFIG_SCHEMA = ProviderConfigSchema(
    name="hybrid_memory",
    label="Hybrid Memory (Local)",
    storage=STORAGE_FLAT_JSON,
    fields=(
        ProviderField(
            key="local_embedding_model",
            label="Embedding model",
            kind=KIND_TEXT,
            default="BAAI/bge-small-en-v1.5",
            description="Sentence-transformers model for local embeddings (~130MB).",
            info="If the model fails to load, the plugin falls back to text search automatically.",
            inline=True,
            group="Embeddings",
        ),
        ProviderField(
            key="max_injected_items",
            label="Max injected memories",
            kind=KIND_NUMBER,
            default="8",
            description="Maximum memories auto-injected as context before each turn.",
            inline=True,
            group="Retrieval",
        ),
        ProviderField(
            key="auto_extract",
            label="Auto-extract facts",
            kind=KIND_BOOL,
            default="true",
            description="Extract memory proposals from each conversation turn.",
            info="When enabled, generic patterns and optional LLM fallback create pending proposals. They are not active memory until reviewed; the agent can save explicitly via memory_save.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="llm_fallback",
            label="LLM fallback extraction",
            kind=KIND_BOOL,
            default="true",
            description="Use the host LLM to create proposals when patterns miss facts.",
            info="Adds latency and token cost per turn, but proposals remain pending until reviewed. Disable for regex-only proposals.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="extraction_shadow_diff",
            label="Extraction shadow-diff",
            kind=KIND_BOOL,
            default="false",
            description="Run LLM extraction in parallel with regex and log the diff (validation mode).",
            info="When enabled, always runs LLM extraction alongside regex and logs what each found that the other missed. Does NOT change the actual proposals created — purely attributetic for evaluating LLM-first extraction. Adds latency + token cost on every turn. Check logs for SHADOW_DIFF entries.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="auto_review",
            label="Automatic proposal review",
            kind=KIND_BOOL,
            default="true",
            description="Have the auxiliary LLM review new proposals.",
            info="Obvious junk is quarantined automatically; sensitive or contextless proposals stay pending for confirmation.",
            inline=True,
            group="Extraction",
        ),
        ProviderField(
            key="graph_aware_retrieval",
            label="Graph-aware retrieval",
            kind=KIND_BOOL,
            default="true",
            description="Boost memories supported by graph entities during normal search.",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_retrieval_boost",
            label="Graph boost strength",
            kind=KIND_TEXT,
            default="0.05",
            description="Maximum similarity boost for graph-supported memories (0.0–0.5).",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_inject_candidates",
            label="Inject graph-only candidates",
            kind=KIND_BOOL,
            default="false",
            description="Add memories found only by the graph (not by semantic search) into results.",
            info="Off by default; injecting graph-only candidates adds noise that hurt recall in benchmarks.",
            group="Retrieval",
        ),
        ProviderField(
            key="graph_boost_min_similarity",
            label="Graph boost min similarity",
            kind=KIND_TEXT,
            default="0.15",
            description="Minimum semantic similarity for a memory to receive the graph boost (0.0–1.0).",
            group="Retrieval",
        ),
        ProviderField(
            key="consolidation_enabled",
            label="Automatic consolidation",
            kind=KIND_BOOL,
            default="false",
            description="Enable reversible maintenance of expired and duplicate memories at session end.",
            info="Disabled by default; use memory_maintenance with dry_run=true to preview candidates.",
            group="Maintenance",
        ),
        ProviderField(
            key="reranker_enabled",
            label="Cross-encoder re-ranking",
            kind=KIND_BOOL,
            default="false",
            description="Re-rank top candidates with a cross-encoder for better relevance.",
            info="Uses BAAI/bge-reranker-base (~420MB, downloaded on first use). Experimental: may improve or regress ranking quality. Adds ~300ms per query on CPU. Enable and evaluate with your query set before relying on it.",
            group="Retrieval",
        ),
        ProviderField(
            key="reranker_model",
            label="Reranker model",
            kind=KIND_TEXT,
            default="BAAI/bge-reranker-base",
            description="HuggingFace model ID for the cross-encoder reranker.",
            group="Retrieval",
        ),
        ProviderField(
            key="reranker_top_n",
            label="Reranker pool size",
            kind=KIND_TEXT,
            default="10",
            description="Number of top candidates to re-rank (5-100). Higher = better ranking but slower.",
            group="Retrieval",
        ),
        ProviderField(
            key="context_aware_retrieval",
            label="Context-aware retrieval",
            kind=KIND_BOOL,
            default="true",
            description="Prepend recent conversation context to queries with pronouns/references.",
            info="When a query contains words like 'that', 'he', 'the thing', the last few user messages are prepended to give the embedder context to resolve the reference. Zero latency cost, no LLM calls.",
            group="Retrieval",
        ),
        ProviderField(
            key="context_window_size",
            label="Context window size",
            kind=KIND_TEXT,
            default="3",
            description="Number of recent user messages to use as context (1-10).",
            group="Retrieval",
        ),
        ProviderField(
            key="context_max_chars",
            label="Context max chars",
            kind=KIND_TEXT,
            default="500",
            description="Maximum total characters of context to prepend (100-2000).",
            group="Retrieval",
        ),
        ProviderField(
            key="query_expansion_enabled",
            label="Query expansion",
            kind=KIND_BOOL,
            default="true",
            description="Expand weak queries into sub-queries via LLM for better recall.",
            info="Only fires when the top search result is below a similarity floor (weak results). Uses the host's auxiliary LLM client. Cached for 1 hour. Fail-soft: returns original results if the LLM call fails. Adds ~1-3s latency only on weak queries.",
            group="Retrieval",
        ),
        ProviderField(
            key="query_expansion_similarity_floor",
            label="Expansion similarity floor",
            kind=KIND_TEXT,
            default="0.3",
            description="Trigger expansion when top hit similarity is below this (0.0-1.0).",
            group="Retrieval",
        ),
        ProviderField(
            key="llm_model",
            label="LLM model",
            kind=KIND_TEXT,
            default="",
            description="Model ID for auxiliary LLM tasks (extraction, review, query expansion). Empty = use auxiliary client default.",
            info="Example: 'google/gemini-3.6-flash', 'openai/gpt-4o-mini', 'anthropic/claude-3.5-sonnet'. Leave empty to use the host's configured auxiliary model. Changing this updates all LLM-based memory operations.",
            group="LLM",
        ),
        ProviderField(
            key="entity_aliases",
            label="Entity aliases",
            kind=KIND_TEXT,
            default="",
            description="JSON mapping of aliases to canonical entity names for retrieval.",
            info='Example: {"my role": "Sam", "the role": "Sam", "the property": "the-property"}. When a search query contains an alias, the system also searches for the canonical entity in the graph. This fixes "tell me about my role" failing to find Entity-A memories.',
            group="Retrieval",
        ),
        ProviderField(
            key="llm_provider",
            label="LLM provider",
            kind=KIND_TEXT,
            default="",
            description="Provider override for auxiliary LLM tasks. Empty = use auxiliary client default.",
            info="Example: 'openrouter', 'openai', 'anthropic'. Leave empty to use the host's configured provider.",
            group="LLM",
        ),
        ProviderField(
            key="storage_mode",
            label="Storage mode",
            kind=KIND_SELECT,
            default="shared_service",
            description="Use one local memory service for all Hermes surfaces.",
            info="Shared service prevents desktop/gateway split-brain and DuckDB writer locks. Direct mode is for attributetics only.",
            options=(
                ProviderFieldOption("shared_service", "Shared service"),
                ProviderFieldOption("local", "Direct files"),
            ),
            group="Storage",
        ),
        ProviderField(
            key="database_filename",
            label="DuckDB filename",
            kind=KIND_TEXT,
            default="hybrid_memory.duckdb",
            description="DuckDB database filename (stored in HERMES_HOME).",
            group="Storage",
        ),
        ProviderField(
            key="graph_dirname",
            label="Kuzu graph directory",
            kind=KIND_TEXT,
            default="hybrid_memory_kuzu",
            description="Kuzu graph database directory (stored in HERMES_HOME).",
            group="Storage",
        ),
    ),
)
